#define _CRT_SECURE_NO_WARNINGS

/*CONSOLE COLORS*/

#define HIGHLIGHT 15
#define REGULAR 8

/*CONSTANT INDICATORS*/

#define MAX_PLAYER_NAME_LENGTH 100
#define FINISH_SUCCESS -2
#define FINISH_FAILURE -3
#define NOT_FINISH -4       
